on:
  workflow_dispatch:
  schedule:
  - cron: '27 22 * * *'

name: CISA Log4J
  scheduled:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
    with:
      cache-version: 2
      extra-packages: any::tidyverse, any::rvest
      needs: |
        website
        coverage
    - name: Process CISA Log4J Vendor
        run: R --silent --no-echo --file=log4j_vendor_response.R